# Generated by Django 5.2.11 on 2026-04-22 01:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('local', '0001_initial'),
        ('producto', '0002_producto_unidad_medida'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('finalizado', 'Finalizado')], default='borrador', max_length=20)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteos_stock_creados', to='usuario.usuario')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteos_stock', to='local.local')),
            ],
            options={
                'db_table': 'conteo_stock',
                'unique_together': {('local', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='ItemConteoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad_conteada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conteo_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_conteo_stock', to='conteostock.conteostock')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_conteo_stock', to='producto.producto')),
            ],
            options={
                'db_table': 'item_conteo_stock',
                'unique_together': {('conteo_stock', 'producto')},
            },
        ),
    ]
