# Generated by Django 5.2.11 on 2026-04-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='cantidad_maxima_de_conteo_stock',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cantidad_maxima_de_locales',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cantidad_maxima_de_productos',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cantidad_maxima_de_usuarios',
            field=models.IntegerField(default=10),
        ),
    ]
