# Generated by Django 5.2.11 on 2026-04-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_cuenta_cantidad_maxima_de_conteo_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='cantidad_maxima_unidadades_de_medida',
            field=models.IntegerField(default=50),
        ),
    ]
