# Generated by Django 5.2.11 on 2026-04-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(default='unidades', max_length=50),
        ),
    ]
