# Generated by Django 5.2.11 on 2026-04-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_cuenta_cantidad_maxima_de_conteo_stock_and_more'),
        ('producto', '0003_alter_producto_unidad_medida'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('nombre', 'unidad_medida', 'cuenta')},
        ),
    ]
