# Generated by Django 5.2.11 on 2026-04-30 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuenta', '0002_cuenta_cantidad_maxima_de_conteo_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_medida', to='cuenta.cuenta')),
            ],
            options={
                'db_table': 'unidad_medida',
                'unique_together': {('nombre', 'cuenta')},
            },
        ),
    ]
