# Generated by Django 5.2.11 on 2026-04-22 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('local', '0001_initial'),
        ('producto', '0002_producto_unidad_medida'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad_objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_stock', to='local.local')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_stock', to='producto.producto')),
            ],
            options={
                'db_table': 'plantilla_stock',
                'unique_together': {('local', 'producto')},
            },
        ),
    ]
